# Analyses not used in Phone Manuscript


Ordination with both fingers coded together - essentially pseudoreplication. But index fingers tell pretty much the same story. 




Created and compared Bray to Canberra - Bray fails to find subtle diffs between phones and fingers, so used Canberra. 


```{r adonisTables,results='asis'}
print(xtable(adonis(rw.25.bray ~ map$gender)$aov.tab), type='html')
print(xtable(adonis(rw.25.can ~ map$gender)$aov.tab), type='html')
```



```{r brayGenderAdonis,results='asis'}
bray.phones <- as.dist(as.matrix(rw.25.bray)[map$location == 'phone', map$location == 'phone'])
map.phones <- map[map$location == 'phone', ]
bray.fingers <- as.dist(as.matrix(rw.25.bray)[map$location != 'phone', map$location != 'phone'])
map.fingers <- map[map$location != 'phone', ]

print(xtable(adonis(bray.phones ~ map.phones$gender)$aov.tab), type='html')
print(xtable(adonis(bray.fingers ~ map.fingers$gender)$aov.tab), type='html')
```


```{r brayPhoneFingersAdonis,results='asis'} 
bray.index.phone.f <- as.dist(as.matrix(rw.25.bray)[intersect(c(index,p),f), intersect(c(index,p),f)])
map.index.phone.f <- map[intersect(c(index,p),f), ]
bray.index.phone.m <- as.dist(as.matrix(rw.25.bray)[intersect(c(index,p),m), intersect(c(index,p),m)])
map.index.phone.m <- map[intersect(c(index,p),m), ]

bray.thumb.phone.f <- as.dist(as.matrix(rw.25.bray)[intersect(c(thumb,p),f), intersect(c(thumb,p),f)])
map.thumb.phone.f <- map[intersect(c(index,p),f), ]
bray.thumb.phone.m <- as.dist(as.matrix(rw.25.bray)[intersect(c(thumb,p),m), intersect(c(thumb,p),m)])
map.thumb.phone.m <- map[intersect(c(thumb,p),m), ]

bray.finger.phone.f <- as.dist(as.matrix(rw.25.bray)[f, f])
map.finger.phone.f <- map[f, ]
bray.finger.phone.m <- as.dist(as.matrix(rw.25.bray)[m, m])
map.finger.phone.m <- map[m, ]

print(xtable(adonis(bray.index.phone.f ~ map.index.phone.f$location)$aov.tab), type='html')
print(xtable(adonis(bray.index.phone.m ~ map.index.phone.m$location)$aov.tab), type='html')
print(xtable(adonis(bray.thumb.phone.f ~ map.thumb.phone.f$location)$aov.tab), type='html')
print(xtable(adonis(bray.thumb.phone.m ~ map.thumb.phone.m$location)$aov.tab), type='html')
print(xtable(adonis(bray.finger.phone.f ~ map.finger.phone.f$location2)$aov.tab), type='html')
print(xtable(adonis(bray.finger.phone.m ~ map.finger.phone.m$location2)$aov.tab), type='html')
```




this from pb  contamination script for side by side barplots 

```{r}
for(i in 11:2) {

  # start empty
  xup <- xdown <- yup <- ydown <- NULL
  
  # begin loop with contamination bar corners
  yup <- rep(con.cum[i], 2)
  # other contamination corners
  ydown <- rep(con.cum[i-1], 2)
  # x coordinates, one gets reversed in plotting
  xup <- xdown <- c(1,2)
  
  # if also in next bar, add bar coordinates
  if(names(con.cum)[i] %in% names(unocc.cum.1000)) {
    ucu <- which(names(unocc.cum.1000) == names(con.cum)[i])
    yup <- c(yup, rep(unocc.cum.1000[ucu], 2))
    ydown <- c(ydown, rep(unocc.cum.1000[ucu-1], 2))
    xup <- xdown <- c(xup, 3,4)
  }
  # same for third bar
  if(names(con.cum)[i] %in% names(occ.cum.1000)) {
    ocu <- which(names(occ.cum.1000) == names(con.cum)[i])
    yup <- c(yup, rep(occ.cum.1000[ocu], 2))
    ydown <- c(ydown, rep(occ.cum.1000[ocu-1], 2))
    xup <- xdown <- c(xup, 5,6)
  }

  # extra stuff for stacked margins
  par(mar=c(3,3,3,3))
  if(i %in% c(7, 2)) {par(mar=c(8,3,3,3))}
  barplot(top.10, col=c('gray30', rep('gray93', 10)), border='gray30', space=1, 
          yaxt='n')  
  if(i %in% c(7, 2)) {
    par(las=2)
    mtext(c('control', 'unoccupied', 'occupied'), side=1, at=c(1.5, 3.5, 5.5), 
          cex=.8, line=.2)}
  
  # stuff for regular margins
  par(las=1)
  if(!i %in% c(7, 2)) {
    par(las=2)
    mtext(c('c', 'u', 'o'), side=1, at=c(1.5, 3.5, 5.5), cex=.8, line=.2)}
  par(las=1)
  if(i %in% 11:7) {
    axis(2, at=c(0, .5, 1), labels=c(0, 50, 100))
  }
  if(i %in% 2:6) {
    axis(4, at=c(0, .5, 1), labels=c(0, 50, 100))
  }
  
  # now all polygons should be in place. 
  polygon(c(xup, rev(xdown)), c(yup, rev(ydown)), col=rgb(0,0,0,.3))
} 


```
